USE [master]
GO

/****** Object:  Database [AutoServ]    Script Date: 4/13/2024 3:32:27 AM ******/
CREATE DATABASE [AutoServ]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AutoServ', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\AutoServ.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'AutoServ_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\AutoServ_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AutoServ].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [AutoServ] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [AutoServ] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [AutoServ] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [AutoServ] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [AutoServ] SET ARITHABORT OFF 
GO

ALTER DATABASE [AutoServ] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [AutoServ] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [AutoServ] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [AutoServ] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [AutoServ] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [AutoServ] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [AutoServ] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [AutoServ] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [AutoServ] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [AutoServ] SET  DISABLE_BROKER 
GO

ALTER DATABASE [AutoServ] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [AutoServ] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [AutoServ] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [AutoServ] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [AutoServ] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [AutoServ] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [AutoServ] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [AutoServ] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [AutoServ] SET  MULTI_USER 
GO

ALTER DATABASE [AutoServ] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [AutoServ] SET DB_CHAINING OFF 
GO

ALTER DATABASE [AutoServ] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [AutoServ] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [AutoServ] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [AutoServ] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [AutoServ] SET QUERY_STORE = OFF
GO

ALTER DATABASE [AutoServ] SET  READ_WRITE 
GO

