USE [master]
GO

/****** Object:  Database [BeautySalon]    Script Date: 4/13/2024 3:32:09 AM ******/
CREATE DATABASE [BeautySalon]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BeautySalon', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\BeautySalon.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BeautySalon_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\BeautySalon_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BeautySalon].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BeautySalon] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BeautySalon] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BeautySalon] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BeautySalon] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BeautySalon] SET ARITHABORT OFF 
GO

ALTER DATABASE [BeautySalon] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BeautySalon] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BeautySalon] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BeautySalon] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BeautySalon] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BeautySalon] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BeautySalon] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BeautySalon] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BeautySalon] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BeautySalon] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BeautySalon] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BeautySalon] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BeautySalon] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BeautySalon] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BeautySalon] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BeautySalon] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BeautySalon] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BeautySalon] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [BeautySalon] SET  MULTI_USER 
GO

ALTER DATABASE [BeautySalon] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BeautySalon] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BeautySalon] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BeautySalon] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [BeautySalon] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BeautySalon] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [BeautySalon] SET QUERY_STORE = OFF
GO

ALTER DATABASE [BeautySalon] SET  READ_WRITE 
GO

