USE [master]
GO

/****** Object:  Database [Poprijonok]    Script Date: 4/13/2024 3:31:06 AM ******/
CREATE DATABASE [Poprijonok]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Poprijonok', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Poprijonok.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Poprijonok_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Poprijonok_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Poprijonok].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Poprijonok] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Poprijonok] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Poprijonok] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Poprijonok] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Poprijonok] SET ARITHABORT OFF 
GO

ALTER DATABASE [Poprijonok] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Poprijonok] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Poprijonok] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Poprijonok] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Poprijonok] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Poprijonok] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Poprijonok] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Poprijonok] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Poprijonok] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Poprijonok] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Poprijonok] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Poprijonok] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Poprijonok] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Poprijonok] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Poprijonok] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Poprijonok] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Poprijonok] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Poprijonok] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Poprijonok] SET  MULTI_USER 
GO

ALTER DATABASE [Poprijonok] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Poprijonok] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Poprijonok] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Poprijonok] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Poprijonok] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Poprijonok] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Poprijonok] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Poprijonok] SET  READ_WRITE 
GO

